[[redirects]]
  from = "/welcome"
  to = "/welcome/im-new"
  status = 200

[[redirects]]
  from = "/worship"
  to = "/worship/live"
  status = 200

[[redirects]]
  from = "/connect"
  to = "/connect/events"
  status = 200

[[redirects]]
  from = "/who-we-are"
  to = "/who-we-are/mission-and-beliefs"
  status = 200

[[redirects]]
  from = "/resources/blog"
  to = "/resources"