[[plugins]]
  package = "@netlify/plugin-a11y"
  [plugins.inputs]
    failWithIssues = false

[[redirects]]
  from = "/welcome"
  to = "/welcome/im-new"

[[redirects]]
  from = "/worship"
  to = "/worship/live"

[[redirects]]
  from = "/connect"
  to = "/connect/events"

[[redirects]]
  from = "/who-we-are"
  to = "/who-we-are/mission-and-beliefs"

[[redirects]]
  from = "/resources/blog"
  to = "/resources"