# [[plugins]]
#  package = "@netlify/plugin-a11y"
#  [plugins.inputs]
#    failWithIssues = false
#    ignoreGuidelines = ['WCAG2AA.Principle1.Guideline1_4.1_4_3.G18', 'WCAG2AA.Principle1.Guideline1_4.1_4_3.G145']
[[redirects]]
  from = "/welcome"
  to = "/welcome/im-new"

[[redirects]]
  from = "/worship"
  to = "/worship/live"

[[redirects]]
  from = "/connect"
  to = "/connect/events"

[[redirects]]
  from = "/who-we-are"
  to = "/who-we-are/mission-and-beliefs"

[[redirects]]
  from = "/resources/blog"
  to = "/resources"

[functions]
  node_bundler = 'esbuild'